### ISSUE TITLE
Using the Messaging in ASP MVC Application

### ISSUE THREAD

**Issue by devmondo** [moonavw/NPatterns#1]
hi, 
i really loved your Messaging code, but could you mind please giving me and example of how to use it in an ASP MVC Application?

thanks in advanced.

**Comment by moonavw** [comment]
hi,
I update the wiki pages, you may find how to use it.
not only aspnet mvc application could use message bus, so my sample shows the steps without touching aspnet mvc.

**Comment by devmondo** [comment]
thanks a lot man, i am still lost and not able to get handlers to get invoked, no errors but nothing happens , i am not using IOC but i still want the auto Discovery, and correct me if i am wrong, but does it not that ServiceLocator can do the Job of IOC for this ? 

here is what i am doing 

i created a test Message

```
public class TestMessage
{
    public string Signle { get; set; }
}
```

and then i have created this Static Bus as you recommended 

 public  static class MessageBusStatic
 {
    public static IMessageBus Bus = new MessageBus();

 }

then i created the Handler

```
public class MyHandler : IHandler<TestMessage>
{
    public void Handle(TestMessage message)
    {
        message.Signle =message.Signle+ "-bbbbb";
    }
}
```

then in my controller i did this in an Action
public ActionResult Bus()
        {

```
        var testMessage = new TestMessage();
        testMessage.Signle = "aaaa";
        MessageBusStatic.Bus.Publish(testMessage);




        return Content(testMessage.Signle);
    }
```

**Comment by moonavw** [comment]
if no IoC, then you need register the handler manually.

```
Bus.Subscribe<TestMessage>(MyHandler.Handle);
```

I added a unit test for message bus as the sample, you will definitely get it work after going through that test case.
please find it in the NPatterns.Tests

**Comment by devmondo** [comment]
thank you so much man for this help and code example, 
could i ask please if it is possible to register multiple handlers to handle the Published Event?

**Comment by moonavw** [comment]
yes, of course you may register bunch of handlers.

**Comment by devmondo** [comment]
thank you for the reply :) i was wondering, could we set the order of handlers when the handle the event ?

**Comment by moonavw** [comment]
No, not supported. Message bus just take care of delivering the message to the recipients. It doesn't care about the order, and it doesn't make sense that depends on the order,  since you may add/remove handler at run-time.

**Comment by moonavw** [comment]
but you may register your handlers in a sequence at the beginning, then the published message would be handled in that sequence.

**Comment by devmondo** [comment]
ohh great, so if i register the handlers sequentially they will be ordered, is it possible to add Order Class Attribute as an option, or it is bad as you said ?

**Comment by moonavw** [comment]
Attribute need reflection to get its value, that is not necessary, I think.
I simply made it support ordering by an optional argument when Subscribe

```
bus.Subscribe(handler, order:2);
```

**Comment by devmondo** [comment]
hi again man, 
i have implemented all above, now there is tiny problem, the compiler is giving me the following error
" cant access explicit implementation of'IHandler<TestMeesage>.Handle' "
so i have to create another handle static method like this

```
public class MyHandler : IHandler<TestMessage>
{
    public static void Handle(TestMessage message)
    {
        message.Signle = message.Signle + "-aabbb";

    }

    void IHandler<TestMessage>.Handle(TestMessage message)
    {
    }
}
```

is this right ?
a

another thing is that PublishAsync does not do anything. no errors but nothing is handled

thanks in advanced.

**Comment by moonavw** [comment]
Your tiny problem is caused by calling the method Handle(message) while using explicit implementation of interface IHandler.
Just use implicit implementation of interface might solve your problem.
Or else you need a convert like ((IHandler)myHandler).Handle(message);

Besides, message bus doesn't care implicit or explicit, because it consumes the interface

Regarding your problem of using PublishAsync, I need your code to see what is the problem.
I fully tested the PublishAsync, I guess you already went through the test cases in /src/NPatterns.Tests/MessageBusTest.cs

**Comment by devmondo** [comment]
Man, thanks a lot really for keeping in touch on this, 
i have uploaded test website for you here, could you please check it
http://www.filesend.net/download.php?f=4bd5ddaee7b326706f366a9944013dbf

as for the explicit implicit issue, why is it happening? i have copied your test-code and followed it, is there something i am missing? i want to follow exactly your code.

thanks a lot again.

**Comment by moonavw** [comment]
I read your code, just fix them as follows.

implicit implementation

```
public class MyHandler : IHandler<TestMessage>
{
    public void Handle(TestMessage message)
    {
        message.Signle = message.Signle + "-aabbb";
    }
}
```

explicit implementation

```
public class MyHandler1 : IHandler<TestMessage>
{
    void IHandler<TestMessage>.Handle(TestMessage message)
    {
        message.Signle = message.Signle + "-cccc";
    }
}
```

consuming those 2 implementations

```
var myHandler=new myHandler();//implicit
IHandler myHandler1=new MyHandler1();//explicit
GlobalBus.Bus.Subscribe<TestMessage>(myHandler.Handle);
GlobalBus.Bus.Subscribe<TestMessage>(myHandler1.Handle);
```

another way to consume them by /src/NPatterns/Messaging/MessageBusExtensions.cs

```
using NPatterns.Messaging;//so we can use the MessageBusExtensions

var myHandler=new myHandler();//implicit
var myHanlder1=new MyHandler1();//explicit
GlobalBus.Bus.Subscribe<TestMessage>(myHandler);
GlobalBus.Bus.Subscribe<TestMessage>(myHandler1);
```

**Comment by devmondo** [comment]
thank you so much man, it works now, but still publish async does not work

**Comment by moonavw** [comment]
You returned it as soon as you published the message, while the handlers haven't finished the async task yet.

```
GlobalBus.Bus.PublishAsync(testMessage);
Thread.Sleep(500);//wait for a while, so that handlers could finish their job
return Content(testMessage.Signle);
```

**Comment by devmondo** [comment]
ohh, how stupid i am, if you don't mind, could you explain to me what is the best use of Async ?

**Comment by moonavw** [comment]
When you don't want block main thread.
When you want it could go on next without waiting for handlers finish their jobs.

**Comment by devmondo** [comment]
thank you so much for your patience and help man, all the best :)
