### ISSUE TITLE
Async Messaging

### ISSUE THREAD

**Issue by devmondo** [moonavw/NPatterns#2]
Hi man, 
is this messaging system you have async ?
i mean what if i create send Emails Handlers, will the user have to wait till emails are sent or it will run in the background ?

thanks in advanced

**Comment by moonavw** [comment]
now supported, I wrote new method for it.

```
MessageBus.PublishAsync(message)
```

**Comment by devmondo** [comment]
awesome man, you are great, do i need special thing like adding Async Controller or it is automatic ?

**Comment by moonavw** [comment]
automatically, register handlers as same as before.

**Comment by devmondo** [comment]
great thank you man
