### ISSUE TITLE
implement error notification

### ISSUE THREAD

**Issue by devmondo** [moonavw/NPatterns#3]
Hi again,

is there a way to tell the Bus that if on of the handlers raise an error to stop invoking the rest of the handlers.

thanks in advanced.

**Comment by moonavw** [comment]
that depends on using async or sync publishing.
if using async, it might be already invoked.
if using sync, simply you could add a flag in your message, when previous handler set the flag to true(like cancel=true), then next handler should do nothing when knows cancel=true.

**Comment by devmondo** [comment]
thank you, great idea, i will try to work on it and see if i understand it :)
