### ISSUE TITLE
guarantee of Message Delivery

### ISSUE THREAD

**Issue by devmondo** [moonavw/NPatterns#4]
Hi, 
is there a way to guarantee message delivery, also  could you kindly tell me how i can  inform the bus that async operations are done ? 

thanks in advanced

**Comment by moonavw** [comment]
u may have some events as callback invoked when ur handler finish its job, that indeed means this one done.
but if u want to do something that requires all async handler done, either u need implement ur observer with counter stuff or I need add a callback param to the publishing that doing what u want when all done, as follow:

```
void Publish(message, callbackOnAllDone);
```

regarding the guarantee of message delivery, I think u may like such way in publishing:

```
bool Publish(message, ...);
```

return true if any handler process the message, return false if no one process it.

if u r fine with those above, I will make planning for them.

**Comment by devmondo** [comment]
man, first of all you are awesome, thank you very much for this, i am asking those  questions because now i based all my new work arround your message bus, it is by far for me the easiest and most straight forward one to use.

the way you suggested above is really great it works same like amplify.js, please implement it it will save a lot of reapatative code

now take a typical user registration example, where i want when user register to also get email sent to him and also upgrade him for example to gold membership, these are 2 operations and best be async so threads wont be blocked. with your suggestion above it will work if one of those 2 async operations fails, i will get false in callback which is great.

 another suggestion is i am also concerned about is, i want to know which one of them failed, would it be a good idea to store a hash of those operation and return a list of false/true of those operations to know which one failed ? i think this is important, and maybe we should have option about if i want to cancel all handlers if one fail or continue and send back the list of failed/succeeded ones.

maybe i am stupid with my idea above, but it is really good for logging and knowing what to do next

another question is, with your suggestion above, does it act like c# task.waitall ?

thank you so much man, cant wait for this to be implemented

**Comment by moonavw** [comment]
implemented the method, pls see commits, the unit test would show you the way to use it. 
I must clarify this: the true/false returned by Publish method is not for the sucess/failure of hanlding.
I think u should do this way for ur case:

```
public class UserRegisteredEventMessage
{
    public TheUserRegisteringData Data {get;set;}
    public bool Cancelled {get;set;} //if set true, others which not starting process msg yet shouldn't handle it
    public TheListOfEachHandledResult Results {get;set;}
}
```

then, in each handling, u shall set cancelled=true if got any error (but async way couldn't wait for it, so it is possible that nothing would be cancelled), and add handled result to the list. so in async way, the callbackOnAllDone let u get all results. also the callbackOnAnyDone let u be able to do something each time when the msg handled, even let u know the "cancelled".

**Comment by devmondo** [comment]
Holy god man, i totally appreciate you listening to me, my brain is exploding, my brain is small to digest this instantly, but i am going through the Tests, but i think what you want to say, is that the true/false returned by publish method, indicates that messages is handled or not regardless if it is handled correctly or not, right ?

and callbackOnAllDone or callbackOnAnyDone  will help me to do any action on this event happens, right ?

**Comment by moonavw** [comment]
yes, exactly. And be noticed: if u want the 'callbackOnAnyDone ' be invoked only once, u shall have a flag that indicates it already run then do nothing if the flag true, so to avoid repeating callback.

**Comment by devmondo** [comment]
thank you very much man, this looks awesome, i have to make  tests so i can fully understand it.

on a side note, in terms of performance, is npattern message bus the same like nservice bus and others ?

**Comment by moonavw** [comment]
first u should understand:
npattern msgbus is for messaging among ur app domain, i.e. across assemblies.
nservicebus is for SOA, i.e. across network.

they are totally different.

**Comment by devmondo** [comment]
ohhh, i got it now, so rule of thumb, is that if you need to interact locally use Npattern's Message Bus, but if you want to interact with external services like Paypal for example use NService Bus.

in terms of performance, i think NPattern's message bus is not the Issue here, it just facilitate the communication channel, it all depends on you as developer to make your code right,  am i correct ? :)

**Comment by moonavw** [comment]
yes, correct. Any problems else?

**Comment by devmondo** [comment]
thank you very much, for now none, i really appreciate your help, i am using Npattern all over the place now :)
